#!/usr/bin/env bash

cd $(dirname "$0")/..

docker run -it -p "8081:8080" -v "${HOME}:/content" \
       -v "${PWD}:/content/notebooks"\
       -e "PROJECT_ID=<PROJECT_ID>" \
       gcr.io/cloud-datalab/datalab:local
